blank_issues_enabled: false

contact_links:
  - name: ğŸ’¬ General Discussion or Questions
    url: https://github.com/Grazulex/laravel-atlas/discussions
    about: Please ask general questions, usage help, or share ideas here.

issue_templates:
  - name: ğŸ Bug Report
    description: Report a reproducible bug in Laravel Atlas
    file: bug.yml

  - name: ğŸ§ª Add or improve tests
    description: Request or describe tests to be added or improved
    file: tests.yml

  - name: ğŸ“š Documentation Update
    description: Suggest an update or addition to the documentation
    file: docs.yml

  - name: ğŸ§© Refactor
    description: Suggest an internal code cleanup or structural refactor
    file: refactor.yml